[base]
dimension = 3
output_dir = "./output_msbc_odat"

[solver]
name = "user"

[algorithm]
name = "pamc"
seed = 12345

[algorithm.param]
min_list = [6.0, 0.008, 8.0]
max_list = [8.0, 0.05, 9.2]
step_list = [0.1, 0.005, 0.1]

[algorithm.pamc]
Tnum = 20
bmin = 1e-2
bmax = 1e2
Tlogspace = true
numsteps_annealing = 50
nreplica_per_proc = 1

[runner]
ignore_error = true

[runner.log]
interval = 20